import type { FetchResponse } from '../types'

export const db: FetchResponse = {
  people: [
    {
      id: 1,
      name: 'Ann Henry',
      jobTitle: 'Product manager',
      country: 'Germany',
      salary: 120000,
      currency: 'EUR',
      employment: 'employee',
    },
    {
      id: 2,
      name: 'Vittoria Janson',
      jobTitle: 'Pianist',
      country: 'Italy',
      salary: 70000,
      currency: 'EUR',
      employment: 'contractor',
    },
    {
      id: 3,
      name: 'Philip Alexix',
      jobTitle: 'Software engineer',
      country: 'France',
      salary: 80000,
      currency: 'EUR',
      employment: 'employee',
    },
    {
      id: 4,
      name: 'Annette Williamson',
      jobTitle: 'CEO',
      country: 'United States',
      salary: 200000,
      currency: 'USD',
      employment: 'employee',
    },
    {
      id: 5,
      name: 'Alexander Lazar',
      jobTitle: 'Customer Success',
      country: 'Czech Republic',
      salary: 50000,
      currency: 'USD',
      employment: 'employee',
    },
    {
      id: 6,
      name: 'Jane Doe',
      jobTitle: 'Product Designer',
      country: 'United Kingdom',
      salary: 80000,
      currency: 'GBP',
      employment: 'employee',
    },
    {
      id: 7,
      name: 'Chris Colgan',
      jobTitle: 'QA',
      country: 'Germany',
      salary: 70000,
      currency: 'EUR',
      employment: 'contractor',
    },
  ],
}
